/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finale.project;

import java.io.*;
import java.util.*;

class Customer {

    private final int referenceNumber;
    private final String title;

    // Constructor for Customer class
    public Customer(int referenceNumber, String title) {
        this.referenceNumber = referenceNumber;
        this.title = title;
    }

    // Getter for reference number
    public int getReferenceNumber() {
        return referenceNumber;
    }

    // Getter for title
    public String getTitle() {
        return title;
    }
}

/**
 *
 * @author salih
 */
public class CustomerLoginUI extends javax.swing.JFrame {

    private ArrayList<Customer> customers = new ArrayList<>();

    /**
     * Creates new form NonLibrarianLoginJFrame
     */
    public CustomerLoginUI() {
        initComponents();

        // Load customer information from file
        loadInfoFromFile("CustomerList.txt");

    }

    // Method to load customer information from a file
    private void loadInfoFromFile(String fileName) {
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (!line.isEmpty()) {
                    try {
                        // Read the reference number from the current line
                        int refNum = Integer.parseInt(line);
                        // Read the title from the next line
                        if ((line = reader.readLine()) != null) {
                            String title = line.trim();
                            if (!title.isEmpty()) {
                                customers.add(new Customer(refNum, title));
                            } else {
                                System.err.println("Empty title encountered. Skipping entry.");
                            }
                        } else {
                            System.err.println("No title found for reference number " + refNum + ". Skipping entry.");
                        }
                    } catch (NumberFormatException e) {
                        System.err.println("Invalid reference number format: " + line);
                    }
                } else {
                    System.err.println("Empty line encountered. Skipping entry.");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        customerLoginLabel = new javax.swing.JLabel();
        loginFoundOrNotFoundLabel = new javax.swing.JLabel();
        continueButton = new javax.swing.JToggleButton();
        previousPageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabel.setText("User Number");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        customerLoginLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        customerLoginLabel.setText("Customer Login");

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        previousPageButton.setText("Back To Previous Page");
        previousPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerLoginLabel)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginFoundOrNotFoundLabel))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousPageButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(customerLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginFoundOrNotFoundLabel)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(continueButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(previousPageButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Method to perform linear search for a customer by reference number
    private boolean linearSearch(int refNum) {

        continueButton.setVisible(true);
        for (Customer Customer : customers) {
            if (Customer.getReferenceNumber() == refNum) {
                loginFoundOrNotFoundLabel.setText("Welcome back, " + Customer.getTitle());
                return true;
            }

        }
        loginFoundOrNotFoundLabel.setText("User not found.");
        continueButton.setVisible(false);
        return false;
    }

    // Action performed when Login button is clicked
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        {
            try {
                int refNum = Integer.parseInt(usernameTextField.getText());
                linearSearch(refNum);

            } catch (NumberFormatException e) {
                loginFoundOrNotFoundLabel.setText("Invalid Reference Number");
                continueButton.setVisible(false);
            }

        }

     }//GEN-LAST:event_LoginButtonActionPerformed

    // Action performed when Continue button is clicked
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        CustomerUI jf1 = new CustomerUI();

        jf1.show();
        dispose();     }//GEN-LAST:event_continueButtonActionPerformed

    // Action performed when Previous Page button is clicked
    private void previousPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPageButtonActionPerformed
        MainScreenUI jf2 = new MainScreenUI();

        jf2.show();
        dispose();     }//GEN-LAST:event_previousPageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>F
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton LoginButton;
    javax.swing.JToggleButton continueButton;
    javax.swing.JLabel customerLoginLabel;
    javax.swing.JLabel loginFoundOrNotFoundLabel;
    javax.swing.JButton previousPageButton;
    javax.swing.JLabel usernameLabel;
    javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
